use semblock::validate_equivalent;

#[test]
fn postgres_177_additional_locations_are_not_semantic_fields() {
    for (source, formatted) in [
        (
            "NOTIFY sample_channel, 'message';",
            "NOTIFY\n    sample_channel,\n    'message';",
        ),
        (
            "CREATE TABLE sample (id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1));",
            "CREATE TABLE sample (\n    id int GENERATED BY DEFAULT AS IDENTITY (\n        START WITH 1\n    )\n);",
        ),
        (
            "CREATE SUBSCRIPTION sample CONNECTION 'connection' PUBLICATION sample_publication;",
            "CREATE SUBSCRIPTION sample\nCONNECTION 'connection'\nPUBLICATION sample_publication;",
        ),
    ] {
        validate_equivalent(source, formatted).unwrap();
    }
}
