#!/usr/bin/env python3
"""Generate the complete borrowed child table for the reviewed pg_query API.

This is a maintainer tool, not a build/runtime dependency or a SQL parser.
Input: the two generated Rust API files from the exactly pinned crate.
"""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess

PIN = {
    "protobuf.rs": "28d494a4b193e800c0bbf40adbd0f3a2fa3dead2ee297f5a8e23cec5f48f21f2",
    "node_ref.rs": "5ce1272d672b3f02dea80a982199b31030817213d61c2be15c068a98ca368357",
}


def generate(root):
    sources = {}
    for name, expected in PIN.items():
        content = (root / "src" / name).read_bytes()
        if hashlib.sha256(content).hexdigest() != expected:
            raise ValueError(f"unreviewed pg_query input: {name}")
        sources[name] = content.decode()
    variants = dict(re.findall(r"^    (\w+)\(&'a protobuf::(\w+)\),", sources["node_ref.rs"], re.M))
    structs = dict(re.findall(r"^pub struct (\w+) \{(.*?)\}", sources["protobuf.rs"], re.S | re.M))
    if len(variants) != 268:
        raise ValueError("unreviewed NodeRef variant count")
    by_type = {name: variant for variant, name in variants.items()}
    arms, leaves = [], []
    for variant, name in variants.items():
        body = structs[name]
        fields = re.findall(r"pub (\w+): (.*?),\n(?=    (?:#|pub)|\})", body + "}", re.S)
        if len(fields) != len(re.findall(r"\bpub \w+:", body)):
            raise ValueError(f"unparsed protobuf fields in {name}")
        actions = []
        for field, field_type in fields:
            field_type = "".join(field_type.split())
            if "::prost::alloc::string::String" in field_type:
                continue
            if field_type.endswith("a_const::Val>"):
                actions.append(f"if let Some(value) = &n.{field} {{ match value {{")
                for tag, kind in [("Ival", "Integer"), ("Fval", "Float"), ("Boolval", "Boolean"), ("Sval", "String"), ("Bsval", "BitString")]:
                    actions.append(f"pg_query::protobuf::a_const::Val::{tag}(value) => out.push(NodeRef::{kind}(value)),")
                actions.append("} }")
                continue
            words = re.findall(r"\b[A-Z]\w*\b", field_type)
            child_type = words[-1] if words else None
            if child_type not in structs:
                continue
            if child_type == "Node":
                if "::Vec<" in field_type:
                    actions.append(f"push_nodes(out, &n.{field});")
                elif "::Option<" in field_type:
                    method = "as_deref" if "::Box<" in field_type else "as_ref"
                    actions.append(f"push_node(out, n.{field}.{method}());")
                else:
                    raise ValueError(f"unreviewed Node field {name}.{field}")
            else:
                child_variant = by_type[child_type]
                if "::Vec<" in field_type:
                    actions.append(f"out.extend(n.{field}.iter().map(NodeRef::{child_variant}));")
                elif "::Option<" in field_type:
                    actions.append(f"if let Some(child) = &n.{field} {{ out.push(NodeRef::{child_variant}(child)); }}")
                else:
                    raise ValueError(f"unreviewed message field {name}.{field}")
        if actions:
            arms.append(f"NodeRef::{variant}(n) => {{\n" + "\n".join(actions) + "\n},")
        else:
            leaves.append(f"NodeRef::{variant}(_)")
    arms.append(" | ".join(leaves) + " => {},")
    output = '''// @generated by scripts/generate-ast-children.py; do not edit by hand.
// pg_query 6.2.1, upstream c780e49d095c7c97def832e45ada3f559d5b42cf.
// Schema/API attribution and license: THIRD_PARTY_NOTICES.md.
use pg_query::{NodeRef, protobuf::Node};

pub(super) fn children<'a>(node: NodeRef<'a>, out: &mut Vec<NodeRef<'a>>) {
    match node {
''' + "\n".join(arms) + '''
    }
}

fn push_nodes<'a>(out: &mut Vec<NodeRef<'a>>, nodes: &'a [Node]) {
    for node in nodes { push_node(out, Some(node)); }
}

fn push_node<'a>(out: &mut Vec<NodeRef<'a>>, node: Option<&'a Node>) {
    if let Some(node) = node.and_then(|node| node.node.as_ref()) { out.push(node.to_ref()); }
}
'''
    return subprocess.run(["rustfmt", "--edition", "2024", "--config", "newline_style=Unix", "--emit", "stdout"], input=output, text=True, capture_output=True, check=True).stdout


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pg-query-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parent.parent / "src/formatter/ast/children.rs"
    generated = generate(args.pg_query_root)
    if args.check:
        if target.read_bytes() != generated.encode():
            raise SystemExit("AST child table differs from reviewed schema")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(generated.encode())
