// @generated by scripts/generate-ast-children.py; do not edit by hand.
// pg_query 6.2.1, upstream c780e49d095c7c97def832e45ada3f559d5b42cf.
// Schema/API attribution and license: THIRD_PARTY_NOTICES.md.
use pg_query::{NodeRef, protobuf::Node};

pub(super) fn children<'a>(node: NodeRef<'a>, out: &mut Vec<NodeRef<'a>>) {
    match node {
        NodeRef::Alias(n) => {
            push_nodes(out, &n.colnames);
        }
        NodeRef::RangeVar(n) => {
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
        }
        NodeRef::TableFunc(n) => {
            push_nodes(out, &n.ns_uris);
            push_nodes(out, &n.ns_names);
            push_node(out, n.docexpr.as_deref());
            push_node(out, n.rowexpr.as_deref());
            push_nodes(out, &n.colnames);
            push_nodes(out, &n.coltypes);
            push_nodes(out, &n.coltypmods);
            push_nodes(out, &n.colcollations);
            push_nodes(out, &n.colexprs);
            push_nodes(out, &n.coldefexprs);
            push_nodes(out, &n.colvalexprs);
            push_nodes(out, &n.passingvalexprs);
            push_node(out, n.plan.as_deref());
        }
        NodeRef::Var(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::Param(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::Aggref(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.aggargtypes);
            push_nodes(out, &n.aggdirectargs);
            push_nodes(out, &n.args);
            push_nodes(out, &n.aggorder);
            push_nodes(out, &n.aggdistinct);
            push_node(out, n.aggfilter.as_deref());
        }
        NodeRef::GroupingFunc(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
            push_nodes(out, &n.refs);
        }
        NodeRef::WindowFunc(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
            push_node(out, n.aggfilter.as_deref());
            push_nodes(out, &n.run_condition);
        }
        NodeRef::SubscriptingRef(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.refupperindexpr);
            push_nodes(out, &n.reflowerindexpr);
            push_node(out, n.refexpr.as_deref());
            push_node(out, n.refassgnexpr.as_deref());
        }
        NodeRef::FuncExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::NamedArgExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::OpExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::DistinctExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::NullIfExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::ScalarArrayOpExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::BoolExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::SubLink(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.testexpr.as_deref());
            push_nodes(out, &n.oper_name);
            push_node(out, n.subselect.as_deref());
        }
        NodeRef::SubPlan(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.testexpr.as_deref());
            push_nodes(out, &n.param_ids);
            push_nodes(out, &n.set_param);
            push_nodes(out, &n.par_param);
            push_nodes(out, &n.args);
        }
        NodeRef::AlternativeSubPlan(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.subplans);
        }
        NodeRef::FieldSelect(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::FieldStore(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
            push_nodes(out, &n.newvals);
            push_nodes(out, &n.fieldnums);
        }
        NodeRef::RelabelType(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::CoerceViaIo(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::ArrayCoerceExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
            push_node(out, n.elemexpr.as_deref());
        }
        NodeRef::ConvertRowtypeExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::CollateExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::CaseExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
            push_nodes(out, &n.args);
            push_node(out, n.defresult.as_deref());
        }
        NodeRef::CaseWhen(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.expr.as_deref());
            push_node(out, n.result.as_deref());
        }
        NodeRef::CaseTestExpr(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::ArrayExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.elements);
        }
        NodeRef::RowExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
            push_nodes(out, &n.colnames);
        }
        NodeRef::RowCompareExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.opnos);
            push_nodes(out, &n.opfamilies);
            push_nodes(out, &n.inputcollids);
            push_nodes(out, &n.largs);
            push_nodes(out, &n.rargs);
        }
        NodeRef::CoalesceExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::MinMaxExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
        }
        NodeRef::SqlvalueFunction(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::XmlExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.named_args);
            push_nodes(out, &n.arg_names);
            push_nodes(out, &n.args);
        }
        NodeRef::NullTest(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::BooleanTest(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::CoerceToDomain(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::CoerceToDomainValue(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::SetToDefault(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::CurrentOfExpr(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::NextValueExpr(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::InferenceElem(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.expr.as_deref());
        }
        NodeRef::TargetEntry(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.expr.as_deref());
        }
        NodeRef::JoinExpr(n) => {
            push_node(out, n.larg.as_deref());
            push_node(out, n.rarg.as_deref());
            push_nodes(out, &n.using_clause);
            if let Some(child) = &n.join_using_alias {
                out.push(NodeRef::Alias(child));
            }
            push_node(out, n.quals.as_deref());
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
        }
        NodeRef::FromExpr(n) => {
            push_nodes(out, &n.fromlist);
            push_node(out, n.quals.as_deref());
        }
        NodeRef::OnConflictExpr(n) => {
            push_nodes(out, &n.arbiter_elems);
            push_node(out, n.arbiter_where.as_deref());
            push_nodes(out, &n.on_conflict_set);
            push_node(out, n.on_conflict_where.as_deref());
            push_nodes(out, &n.excl_rel_tlist);
        }
        NodeRef::IntoClause(n) => {
            if let Some(child) = &n.rel {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.col_names);
            push_nodes(out, &n.options);
            push_node(out, n.view_query.as_deref());
        }
        NodeRef::RawStmt(n) => {
            push_node(out, n.stmt.as_deref());
        }
        NodeRef::Query(n) => {
            push_node(out, n.utility_stmt.as_deref());
            push_nodes(out, &n.cte_list);
            push_nodes(out, &n.rtable);
            push_nodes(out, &n.rteperminfos);
            if let Some(child) = &n.jointree {
                out.push(NodeRef::FromExpr(child));
            }
            push_nodes(out, &n.merge_action_list);
            push_node(out, n.merge_join_condition.as_deref());
            push_nodes(out, &n.target_list);
            if let Some(child) = &n.on_conflict {
                out.push(NodeRef::OnConflictExpr(child));
            }
            push_nodes(out, &n.returning_list);
            push_nodes(out, &n.group_clause);
            push_nodes(out, &n.grouping_sets);
            push_node(out, n.having_qual.as_deref());
            push_nodes(out, &n.window_clause);
            push_nodes(out, &n.distinct_clause);
            push_nodes(out, &n.sort_clause);
            push_node(out, n.limit_offset.as_deref());
            push_node(out, n.limit_count.as_deref());
            push_nodes(out, &n.row_marks);
            push_node(out, n.set_operations.as_deref());
            push_nodes(out, &n.constraint_deps);
            push_nodes(out, &n.with_check_options);
        }
        NodeRef::InsertStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.cols);
            push_node(out, n.select_stmt.as_deref());
            if let Some(child) = &n.on_conflict_clause {
                out.push(NodeRef::OnConflictClause(child));
            }
            push_nodes(out, &n.returning_list);
            if let Some(child) = &n.with_clause {
                out.push(NodeRef::WithClause(child));
            }
        }
        NodeRef::DeleteStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.using_clause);
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.returning_list);
            if let Some(child) = &n.with_clause {
                out.push(NodeRef::WithClause(child));
            }
        }
        NodeRef::UpdateStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.target_list);
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.from_clause);
            push_nodes(out, &n.returning_list);
            if let Some(child) = &n.with_clause {
                out.push(NodeRef::WithClause(child));
            }
        }
        NodeRef::SelectStmt(n) => {
            push_nodes(out, &n.distinct_clause);
            if let Some(child) = &n.into_clause {
                out.push(NodeRef::IntoClause(child));
            }
            push_nodes(out, &n.target_list);
            push_nodes(out, &n.from_clause);
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.group_clause);
            push_node(out, n.having_clause.as_deref());
            push_nodes(out, &n.window_clause);
            push_nodes(out, &n.values_lists);
            push_nodes(out, &n.sort_clause);
            push_node(out, n.limit_offset.as_deref());
            push_node(out, n.limit_count.as_deref());
            push_nodes(out, &n.locking_clause);
            if let Some(child) = &n.with_clause {
                out.push(NodeRef::WithClause(child));
            }
            if let Some(child) = &n.larg {
                out.push(NodeRef::SelectStmt(child));
            }
            if let Some(child) = &n.rarg {
                out.push(NodeRef::SelectStmt(child));
            }
        }
        NodeRef::AlterTableStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.cmds);
        }
        NodeRef::AlterTableCmd(n) => {
            if let Some(child) = &n.newowner {
                out.push(NodeRef::RoleSpec(child));
            }
            push_node(out, n.def.as_deref());
        }
        NodeRef::AlterDomainStmt(n) => {
            push_nodes(out, &n.type_name);
            push_node(out, n.def.as_deref());
        }
        NodeRef::SetOperationStmt(n) => {
            push_node(out, n.larg.as_deref());
            push_node(out, n.rarg.as_deref());
            push_nodes(out, &n.col_types);
            push_nodes(out, &n.col_typmods);
            push_nodes(out, &n.col_collations);
            push_nodes(out, &n.group_clauses);
        }
        NodeRef::GrantStmt(n) => {
            push_nodes(out, &n.objects);
            push_nodes(out, &n.privileges);
            push_nodes(out, &n.grantees);
            if let Some(child) = &n.grantor {
                out.push(NodeRef::RoleSpec(child));
            }
        }
        NodeRef::GrantRoleStmt(n) => {
            push_nodes(out, &n.granted_roles);
            push_nodes(out, &n.grantee_roles);
            push_nodes(out, &n.opt);
            if let Some(child) = &n.grantor {
                out.push(NodeRef::RoleSpec(child));
            }
        }
        NodeRef::AlterDefaultPrivilegesStmt(n) => {
            push_nodes(out, &n.options);
            if let Some(child) = &n.action {
                out.push(NodeRef::GrantStmt(child));
            }
        }
        NodeRef::ClusterStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.params);
        }
        NodeRef::CopyStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.query.as_deref());
            push_nodes(out, &n.attlist);
            push_nodes(out, &n.options);
            push_node(out, n.where_clause.as_deref());
        }
        NodeRef::CreateStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.table_elts);
            push_nodes(out, &n.inh_relations);
            if let Some(child) = &n.partbound {
                out.push(NodeRef::PartitionBoundSpec(child));
            }
            if let Some(child) = &n.partspec {
                out.push(NodeRef::PartitionSpec(child));
            }
            if let Some(child) = &n.of_typename {
                out.push(NodeRef::TypeName(child));
            }
            push_nodes(out, &n.constraints);
            push_nodes(out, &n.options);
        }
        NodeRef::DefineStmt(n) => {
            push_nodes(out, &n.defnames);
            push_nodes(out, &n.args);
            push_nodes(out, &n.definition);
        }
        NodeRef::DropStmt(n) => {
            push_nodes(out, &n.objects);
        }
        NodeRef::TruncateStmt(n) => {
            push_nodes(out, &n.relations);
        }
        NodeRef::CommentStmt(n) => {
            push_node(out, n.object.as_deref());
        }
        NodeRef::IndexStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.index_params);
            push_nodes(out, &n.index_including_params);
            push_nodes(out, &n.options);
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.exclude_op_names);
        }
        NodeRef::CreateFunctionStmt(n) => {
            push_nodes(out, &n.funcname);
            push_nodes(out, &n.parameters);
            if let Some(child) = &n.return_type {
                out.push(NodeRef::TypeName(child));
            }
            push_nodes(out, &n.options);
            push_node(out, n.sql_body.as_deref());
        }
        NodeRef::AlterFunctionStmt(n) => {
            if let Some(child) = &n.func {
                out.push(NodeRef::ObjectWithArgs(child));
            }
            push_nodes(out, &n.actions);
        }
        NodeRef::DoStmt(n) => {
            push_nodes(out, &n.args);
        }
        NodeRef::RenameStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.object.as_deref());
        }
        NodeRef::RuleStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.actions);
        }
        NodeRef::TransactionStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::ViewStmt(n) => {
            if let Some(child) = &n.view {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.aliases);
            push_node(out, n.query.as_deref());
            push_nodes(out, &n.options);
        }
        NodeRef::CreateDomainStmt(n) => {
            push_nodes(out, &n.domainname);
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.coll_clause {
                out.push(NodeRef::CollateClause(child));
            }
            push_nodes(out, &n.constraints);
        }
        NodeRef::CreatedbStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::DropdbStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::VacuumStmt(n) => {
            push_nodes(out, &n.options);
            push_nodes(out, &n.rels);
        }
        NodeRef::ExplainStmt(n) => {
            push_node(out, n.query.as_deref());
            push_nodes(out, &n.options);
        }
        NodeRef::CreateTableAsStmt(n) => {
            push_node(out, n.query.as_deref());
            if let Some(child) = &n.into {
                out.push(NodeRef::IntoClause(child));
            }
        }
        NodeRef::CreateSeqStmt(n) => {
            if let Some(child) = &n.sequence {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::AlterSeqStmt(n) => {
            if let Some(child) = &n.sequence {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::VariableSetStmt(n) => {
            push_nodes(out, &n.args);
        }
        NodeRef::CreateTrigStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.funcname);
            push_nodes(out, &n.args);
            push_nodes(out, &n.columns);
            push_node(out, n.when_clause.as_deref());
            push_nodes(out, &n.transition_rels);
            if let Some(child) = &n.constrrel {
                out.push(NodeRef::RangeVar(child));
            }
        }
        NodeRef::CreatePlangStmt(n) => {
            push_nodes(out, &n.plhandler);
            push_nodes(out, &n.plinline);
            push_nodes(out, &n.plvalidator);
        }
        NodeRef::CreateRoleStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterRoleStmt(n) => {
            if let Some(child) = &n.role {
                out.push(NodeRef::RoleSpec(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::DropRoleStmt(n) => {
            push_nodes(out, &n.roles);
        }
        NodeRef::LockStmt(n) => {
            push_nodes(out, &n.relations);
        }
        NodeRef::ConstraintsSetStmt(n) => {
            push_nodes(out, &n.constraints);
        }
        NodeRef::ReindexStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.params);
        }
        NodeRef::CreateSchemaStmt(n) => {
            if let Some(child) = &n.authrole {
                out.push(NodeRef::RoleSpec(child));
            }
            push_nodes(out, &n.schema_elts);
        }
        NodeRef::AlterDatabaseStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterDatabaseSetStmt(n) => {
            if let Some(child) = &n.setstmt {
                out.push(NodeRef::VariableSetStmt(child));
            }
        }
        NodeRef::AlterRoleSetStmt(n) => {
            if let Some(child) = &n.role {
                out.push(NodeRef::RoleSpec(child));
            }
            if let Some(child) = &n.setstmt {
                out.push(NodeRef::VariableSetStmt(child));
            }
        }
        NodeRef::CreateConversionStmt(n) => {
            push_nodes(out, &n.conversion_name);
            push_nodes(out, &n.func_name);
        }
        NodeRef::CreateCastStmt(n) => {
            if let Some(child) = &n.sourcetype {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.targettype {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.func {
                out.push(NodeRef::ObjectWithArgs(child));
            }
        }
        NodeRef::CreateOpClassStmt(n) => {
            push_nodes(out, &n.opclassname);
            push_nodes(out, &n.opfamilyname);
            if let Some(child) = &n.datatype {
                out.push(NodeRef::TypeName(child));
            }
            push_nodes(out, &n.items);
        }
        NodeRef::CreateOpFamilyStmt(n) => {
            push_nodes(out, &n.opfamilyname);
        }
        NodeRef::AlterOpFamilyStmt(n) => {
            push_nodes(out, &n.opfamilyname);
            push_nodes(out, &n.items);
        }
        NodeRef::PrepareStmt(n) => {
            push_nodes(out, &n.argtypes);
            push_node(out, n.query.as_deref());
        }
        NodeRef::ExecuteStmt(n) => {
            push_nodes(out, &n.params);
        }
        NodeRef::DeclareCursorStmt(n) => {
            push_node(out, n.query.as_deref());
        }
        NodeRef::CreateTableSpaceStmt(n) => {
            if let Some(child) = &n.owner {
                out.push(NodeRef::RoleSpec(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::AlterObjectDependsStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.object.as_deref());
            if let Some(child) = &n.extname {
                out.push(NodeRef::String(child));
            }
        }
        NodeRef::AlterObjectSchemaStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.object.as_deref());
        }
        NodeRef::AlterOwnerStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.object.as_deref());
            if let Some(child) = &n.newowner {
                out.push(NodeRef::RoleSpec(child));
            }
        }
        NodeRef::AlterOperatorStmt(n) => {
            if let Some(child) = &n.opername {
                out.push(NodeRef::ObjectWithArgs(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::AlterTypeStmt(n) => {
            push_nodes(out, &n.type_name);
            push_nodes(out, &n.options);
        }
        NodeRef::DropOwnedStmt(n) => {
            push_nodes(out, &n.roles);
        }
        NodeRef::ReassignOwnedStmt(n) => {
            push_nodes(out, &n.roles);
            if let Some(child) = &n.newrole {
                out.push(NodeRef::RoleSpec(child));
            }
        }
        NodeRef::CompositeTypeStmt(n) => {
            if let Some(child) = &n.typevar {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.coldeflist);
        }
        NodeRef::CreateEnumStmt(n) => {
            push_nodes(out, &n.type_name);
            push_nodes(out, &n.vals);
        }
        NodeRef::CreateRangeStmt(n) => {
            push_nodes(out, &n.type_name);
            push_nodes(out, &n.params);
        }
        NodeRef::AlterEnumStmt(n) => {
            push_nodes(out, &n.type_name);
        }
        NodeRef::AlterTsdictionaryStmt(n) => {
            push_nodes(out, &n.dictname);
            push_nodes(out, &n.options);
        }
        NodeRef::AlterTsconfigurationStmt(n) => {
            push_nodes(out, &n.cfgname);
            push_nodes(out, &n.tokentype);
            push_nodes(out, &n.dicts);
        }
        NodeRef::CreateFdwStmt(n) => {
            push_nodes(out, &n.func_options);
            push_nodes(out, &n.options);
        }
        NodeRef::AlterFdwStmt(n) => {
            push_nodes(out, &n.func_options);
            push_nodes(out, &n.options);
        }
        NodeRef::CreateForeignServerStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterForeignServerStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::CreateUserMappingStmt(n) => {
            if let Some(child) = &n.user {
                out.push(NodeRef::RoleSpec(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::AlterUserMappingStmt(n) => {
            if let Some(child) = &n.user {
                out.push(NodeRef::RoleSpec(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::DropUserMappingStmt(n) => {
            if let Some(child) = &n.user {
                out.push(NodeRef::RoleSpec(child));
            }
        }
        NodeRef::AlterTableSpaceOptionsStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterTableMoveAllStmt(n) => {
            push_nodes(out, &n.roles);
        }
        NodeRef::SecLabelStmt(n) => {
            push_node(out, n.object.as_deref());
        }
        NodeRef::CreateForeignTableStmt(n) => {
            if let Some(child) = &n.base_stmt {
                out.push(NodeRef::CreateStmt(child));
            }
            push_nodes(out, &n.options);
        }
        NodeRef::ImportForeignSchemaStmt(n) => {
            push_nodes(out, &n.table_list);
            push_nodes(out, &n.options);
        }
        NodeRef::CreateExtensionStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterExtensionStmt(n) => {
            push_nodes(out, &n.options);
        }
        NodeRef::AlterExtensionContentsStmt(n) => {
            push_node(out, n.object.as_deref());
        }
        NodeRef::CreateEventTrigStmt(n) => {
            push_nodes(out, &n.whenclause);
            push_nodes(out, &n.funcname);
        }
        NodeRef::RefreshMatViewStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
        }
        NodeRef::AlterSystemStmt(n) => {
            if let Some(child) = &n.setstmt {
                out.push(NodeRef::VariableSetStmt(child));
            }
        }
        NodeRef::CreatePolicyStmt(n) => {
            if let Some(child) = &n.table {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.roles);
            push_node(out, n.qual.as_deref());
            push_node(out, n.with_check.as_deref());
        }
        NodeRef::AlterPolicyStmt(n) => {
            if let Some(child) = &n.table {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.roles);
            push_node(out, n.qual.as_deref());
            push_node(out, n.with_check.as_deref());
        }
        NodeRef::CreateTransformStmt(n) => {
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.fromsql {
                out.push(NodeRef::ObjectWithArgs(child));
            }
            if let Some(child) = &n.tosql {
                out.push(NodeRef::ObjectWithArgs(child));
            }
        }
        NodeRef::CreateAmStmt(n) => {
            push_nodes(out, &n.handler_name);
        }
        NodeRef::CreatePublicationStmt(n) => {
            push_nodes(out, &n.options);
            push_nodes(out, &n.pubobjects);
        }
        NodeRef::AlterPublicationStmt(n) => {
            push_nodes(out, &n.options);
            push_nodes(out, &n.pubobjects);
        }
        NodeRef::CreateSubscriptionStmt(n) => {
            push_nodes(out, &n.publication);
            push_nodes(out, &n.options);
        }
        NodeRef::AlterSubscriptionStmt(n) => {
            push_nodes(out, &n.publication);
            push_nodes(out, &n.options);
        }
        NodeRef::CreateStatsStmt(n) => {
            push_nodes(out, &n.defnames);
            push_nodes(out, &n.stat_types);
            push_nodes(out, &n.exprs);
            push_nodes(out, &n.relations);
        }
        NodeRef::AlterCollationStmt(n) => {
            push_nodes(out, &n.collname);
        }
        NodeRef::CallStmt(n) => {
            if let Some(child) = &n.funccall {
                out.push(NodeRef::FuncCall(child));
            }
            if let Some(child) = &n.funcexpr {
                out.push(NodeRef::FuncExpr(child));
            }
            push_nodes(out, &n.outargs);
        }
        NodeRef::AlterStatsStmt(n) => {
            push_nodes(out, &n.defnames);
            push_node(out, n.stxstattarget.as_deref());
        }
        NodeRef::AExpr(n) => {
            push_nodes(out, &n.name);
            push_node(out, n.lexpr.as_deref());
            push_node(out, n.rexpr.as_deref());
        }
        NodeRef::ColumnRef(n) => {
            push_nodes(out, &n.fields);
        }
        NodeRef::AConst(n) => {
            if let Some(value) = &n.val {
                match value {
                    pg_query::protobuf::a_const::Val::Ival(value) => {
                        out.push(NodeRef::Integer(value))
                    }
                    pg_query::protobuf::a_const::Val::Fval(value) => {
                        out.push(NodeRef::Float(value))
                    }
                    pg_query::protobuf::a_const::Val::Boolval(value) => {
                        out.push(NodeRef::Boolean(value))
                    }
                    pg_query::protobuf::a_const::Val::Sval(value) => {
                        out.push(NodeRef::String(value))
                    }
                    pg_query::protobuf::a_const::Val::Bsval(value) => {
                        out.push(NodeRef::BitString(value))
                    }
                }
            }
        }
        NodeRef::FuncCall(n) => {
            push_nodes(out, &n.funcname);
            push_nodes(out, &n.args);
            push_nodes(out, &n.agg_order);
            push_node(out, n.agg_filter.as_deref());
            if let Some(child) = &n.over {
                out.push(NodeRef::WindowDef(child));
            }
        }
        NodeRef::AIndices(n) => {
            push_node(out, n.lidx.as_deref());
            push_node(out, n.uidx.as_deref());
        }
        NodeRef::AIndirection(n) => {
            push_node(out, n.arg.as_deref());
            push_nodes(out, &n.indirection);
        }
        NodeRef::AArrayExpr(n) => {
            push_nodes(out, &n.elements);
        }
        NodeRef::ResTarget(n) => {
            push_nodes(out, &n.indirection);
            push_node(out, n.val.as_deref());
        }
        NodeRef::MultiAssignRef(n) => {
            push_node(out, n.source.as_deref());
        }
        NodeRef::TypeCast(n) => {
            push_node(out, n.arg.as_deref());
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
        }
        NodeRef::CollateClause(n) => {
            push_node(out, n.arg.as_deref());
            push_nodes(out, &n.collname);
        }
        NodeRef::SortBy(n) => {
            push_node(out, n.node.as_deref());
            push_nodes(out, &n.use_op);
        }
        NodeRef::WindowDef(n) => {
            push_nodes(out, &n.partition_clause);
            push_nodes(out, &n.order_clause);
            push_node(out, n.start_offset.as_deref());
            push_node(out, n.end_offset.as_deref());
        }
        NodeRef::RangeSubselect(n) => {
            push_node(out, n.subquery.as_deref());
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
        }
        NodeRef::RangeFunction(n) => {
            push_nodes(out, &n.functions);
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
            push_nodes(out, &n.coldeflist);
        }
        NodeRef::RangeTableSample(n) => {
            push_node(out, n.relation.as_deref());
            push_nodes(out, &n.method);
            push_nodes(out, &n.args);
            push_node(out, n.repeatable.as_deref());
        }
        NodeRef::RangeTableFunc(n) => {
            push_node(out, n.docexpr.as_deref());
            push_node(out, n.rowexpr.as_deref());
            push_nodes(out, &n.namespaces);
            push_nodes(out, &n.columns);
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
        }
        NodeRef::RangeTableFuncCol(n) => {
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            push_node(out, n.colexpr.as_deref());
            push_node(out, n.coldefexpr.as_deref());
        }
        NodeRef::TypeName(n) => {
            push_nodes(out, &n.names);
            push_nodes(out, &n.typmods);
            push_nodes(out, &n.array_bounds);
        }
        NodeRef::ColumnDef(n) => {
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            push_node(out, n.raw_default.as_deref());
            push_node(out, n.cooked_default.as_deref());
            if let Some(child) = &n.identity_sequence {
                out.push(NodeRef::RangeVar(child));
            }
            if let Some(child) = &n.coll_clause {
                out.push(NodeRef::CollateClause(child));
            }
            push_nodes(out, &n.constraints);
            push_nodes(out, &n.fdwoptions);
        }
        NodeRef::IndexElem(n) => {
            push_node(out, n.expr.as_deref());
            push_nodes(out, &n.collation);
            push_nodes(out, &n.opclass);
            push_nodes(out, &n.opclassopts);
        }
        NodeRef::Constraint(n) => {
            push_node(out, n.raw_expr.as_deref());
            push_nodes(out, &n.keys);
            push_nodes(out, &n.including);
            push_nodes(out, &n.exclusions);
            push_nodes(out, &n.options);
            push_node(out, n.where_clause.as_deref());
            if let Some(child) = &n.pktable {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.fk_attrs);
            push_nodes(out, &n.pk_attrs);
            push_nodes(out, &n.fk_del_set_cols);
            push_nodes(out, &n.old_conpfeqop);
        }
        NodeRef::DefElem(n) => {
            push_node(out, n.arg.as_deref());
        }
        NodeRef::RangeTblEntry(n) => {
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
            if let Some(child) = &n.eref {
                out.push(NodeRef::Alias(child));
            }
            if let Some(child) = &n.tablesample {
                out.push(NodeRef::TableSampleClause(child));
            }
            if let Some(child) = &n.subquery {
                out.push(NodeRef::Query(child));
            }
            push_nodes(out, &n.joinaliasvars);
            push_nodes(out, &n.joinleftcols);
            push_nodes(out, &n.joinrightcols);
            if let Some(child) = &n.join_using_alias {
                out.push(NodeRef::Alias(child));
            }
            push_nodes(out, &n.functions);
            if let Some(child) = &n.tablefunc {
                out.push(NodeRef::TableFunc(child));
            }
            push_nodes(out, &n.values_lists);
            push_nodes(out, &n.coltypes);
            push_nodes(out, &n.coltypmods);
            push_nodes(out, &n.colcollations);
            push_nodes(out, &n.security_quals);
        }
        NodeRef::RangeTblFunction(n) => {
            push_node(out, n.funcexpr.as_deref());
            push_nodes(out, &n.funccolnames);
            push_nodes(out, &n.funccoltypes);
            push_nodes(out, &n.funccoltypmods);
            push_nodes(out, &n.funccolcollations);
        }
        NodeRef::TableSampleClause(n) => {
            push_nodes(out, &n.args);
            push_node(out, n.repeatable.as_deref());
        }
        NodeRef::WithCheckOption(n) => {
            push_node(out, n.qual.as_deref());
        }
        NodeRef::GroupingSet(n) => {
            push_nodes(out, &n.content);
        }
        NodeRef::WindowClause(n) => {
            push_nodes(out, &n.partition_clause);
            push_nodes(out, &n.order_clause);
            push_node(out, n.start_offset.as_deref());
            push_node(out, n.end_offset.as_deref());
        }
        NodeRef::ObjectWithArgs(n) => {
            push_nodes(out, &n.objname);
            push_nodes(out, &n.objargs);
            push_nodes(out, &n.objfuncargs);
        }
        NodeRef::AccessPriv(n) => {
            push_nodes(out, &n.cols);
        }
        NodeRef::CreateOpClassItem(n) => {
            if let Some(child) = &n.name {
                out.push(NodeRef::ObjectWithArgs(child));
            }
            push_nodes(out, &n.order_family);
            push_nodes(out, &n.class_args);
            if let Some(child) = &n.storedtype {
                out.push(NodeRef::TypeName(child));
            }
        }
        NodeRef::TableLikeClause(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
        }
        NodeRef::FunctionParameter(n) => {
            if let Some(child) = &n.arg_type {
                out.push(NodeRef::TypeName(child));
            }
            push_node(out, n.defexpr.as_deref());
        }
        NodeRef::LockingClause(n) => {
            push_nodes(out, &n.locked_rels);
        }
        NodeRef::XmlSerialize(n) => {
            push_node(out, n.expr.as_deref());
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
        }
        NodeRef::WithClause(n) => {
            push_nodes(out, &n.ctes);
        }
        NodeRef::InferClause(n) => {
            push_nodes(out, &n.index_elems);
            push_node(out, n.where_clause.as_deref());
        }
        NodeRef::OnConflictClause(n) => {
            if let Some(child) = &n.infer {
                out.push(NodeRef::InferClause(child));
            }
            push_nodes(out, &n.target_list);
            push_node(out, n.where_clause.as_deref());
        }
        NodeRef::CommonTableExpr(n) => {
            push_nodes(out, &n.aliascolnames);
            push_node(out, n.ctequery.as_deref());
            if let Some(child) = &n.search_clause {
                out.push(NodeRef::CtesearchClause(child));
            }
            if let Some(child) = &n.cycle_clause {
                out.push(NodeRef::CtecycleClause(child));
            }
            push_nodes(out, &n.ctecolnames);
            push_nodes(out, &n.ctecoltypes);
            push_nodes(out, &n.ctecoltypmods);
            push_nodes(out, &n.ctecolcollations);
        }
        NodeRef::PartitionElem(n) => {
            push_node(out, n.expr.as_deref());
            push_nodes(out, &n.collation);
            push_nodes(out, &n.opclass);
        }
        NodeRef::PartitionSpec(n) => {
            push_nodes(out, &n.part_params);
        }
        NodeRef::PartitionBoundSpec(n) => {
            push_nodes(out, &n.listdatums);
            push_nodes(out, &n.lowerdatums);
            push_nodes(out, &n.upperdatums);
        }
        NodeRef::PartitionRangeDatum(n) => {
            push_node(out, n.value.as_deref());
        }
        NodeRef::PartitionCmd(n) => {
            if let Some(child) = &n.name {
                out.push(NodeRef::RangeVar(child));
            }
            if let Some(child) = &n.bound {
                out.push(NodeRef::PartitionBoundSpec(child));
            }
        }
        NodeRef::VacuumRelation(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_nodes(out, &n.va_cols);
        }
        NodeRef::List(n) => {
            push_nodes(out, &n.items);
        }
        NodeRef::IntList(n) => {
            push_nodes(out, &n.items);
        }
        NodeRef::OidList(n) => {
            push_nodes(out, &n.items);
        }
        NodeRef::MergeStmt(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.source_relation.as_deref());
            push_node(out, n.join_condition.as_deref());
            push_nodes(out, &n.merge_when_clauses);
            push_nodes(out, &n.returning_list);
            if let Some(child) = &n.with_clause {
                out.push(NodeRef::WithClause(child));
            }
        }
        NodeRef::MergeAction(n) => {
            push_node(out, n.qual.as_deref());
            push_nodes(out, &n.target_list);
            push_nodes(out, &n.update_colnos);
        }
        NodeRef::ReturnStmt(n) => {
            push_node(out, n.returnval.as_deref());
        }
        NodeRef::PlassignStmt(n) => {
            push_nodes(out, &n.indirection);
            if let Some(child) = &n.val {
                out.push(NodeRef::SelectStmt(child));
            }
        }
        NodeRef::StatsElem(n) => {
            push_node(out, n.expr.as_deref());
        }
        NodeRef::CtesearchClause(n) => {
            push_nodes(out, &n.search_col_list);
        }
        NodeRef::CtecycleClause(n) => {
            push_nodes(out, &n.cycle_col_list);
            push_node(out, n.cycle_mark_value.as_deref());
            push_node(out, n.cycle_mark_default.as_deref());
        }
        NodeRef::MergeWhenClause(n) => {
            push_node(out, n.condition.as_deref());
            push_nodes(out, &n.target_list);
            push_nodes(out, &n.values);
        }
        NodeRef::PublicationObjSpec(n) => {
            if let Some(child) = &n.pubtable {
                out.push(NodeRef::PublicationTable(child));
            }
        }
        NodeRef::PublicationTable(n) => {
            if let Some(child) = &n.relation {
                out.push(NodeRef::RangeVar(child));
            }
            push_node(out, n.where_clause.as_deref());
            push_nodes(out, &n.columns);
        }
        NodeRef::JsonReturning(n) => {
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
        }
        NodeRef::JsonValueExpr(n) => {
            push_node(out, n.raw_expr.as_deref());
            push_node(out, n.formatted_expr.as_deref());
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
        }
        NodeRef::JsonConstructorExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_nodes(out, &n.args);
            push_node(out, n.func.as_deref());
            push_node(out, n.coercion.as_deref());
            if let Some(child) = &n.returning {
                out.push(NodeRef::JsonReturning(child));
            }
        }
        NodeRef::JsonIsPredicate(n) => {
            push_node(out, n.expr.as_deref());
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
        }
        NodeRef::JsonOutput(n) => {
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.returning {
                out.push(NodeRef::JsonReturning(child));
            }
        }
        NodeRef::JsonKeyValue(n) => {
            push_node(out, n.key.as_deref());
            if let Some(child) = &n.value {
                out.push(NodeRef::JsonValueExpr(child));
            }
        }
        NodeRef::JsonObjectConstructor(n) => {
            push_nodes(out, &n.exprs);
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
        }
        NodeRef::JsonArrayConstructor(n) => {
            push_nodes(out, &n.exprs);
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
        }
        NodeRef::JsonArrayQueryConstructor(n) => {
            push_node(out, n.query.as_deref());
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
        }
        NodeRef::JsonAggConstructor(n) => {
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
            push_node(out, n.agg_filter.as_deref());
            push_nodes(out, &n.agg_order);
            if let Some(child) = &n.over {
                out.push(NodeRef::WindowDef(child));
            }
        }
        NodeRef::JsonObjectAgg(n) => {
            if let Some(child) = &n.constructor {
                out.push(NodeRef::JsonAggConstructor(child));
            }
            if let Some(child) = &n.arg {
                out.push(NodeRef::JsonKeyValue(child));
            }
        }
        NodeRef::JsonArrayAgg(n) => {
            if let Some(child) = &n.constructor {
                out.push(NodeRef::JsonAggConstructor(child));
            }
            if let Some(child) = &n.arg {
                out.push(NodeRef::JsonValueExpr(child));
            }
        }
        NodeRef::WindowFuncRunCondition(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.arg.as_deref());
        }
        NodeRef::MergeSupportFunc(n) => {
            push_node(out, n.xpr.as_deref());
        }
        NodeRef::JsonBehavior(n) => {
            push_node(out, n.expr.as_deref());
        }
        NodeRef::JsonExpr(n) => {
            push_node(out, n.xpr.as_deref());
            push_node(out, n.formatted_expr.as_deref());
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
            push_node(out, n.path_spec.as_deref());
            if let Some(child) = &n.returning {
                out.push(NodeRef::JsonReturning(child));
            }
            push_nodes(out, &n.passing_names);
            push_nodes(out, &n.passing_values);
            if let Some(child) = &n.on_empty {
                out.push(NodeRef::JsonBehavior(child));
            }
            if let Some(child) = &n.on_error {
                out.push(NodeRef::JsonBehavior(child));
            }
        }
        NodeRef::JsonTablePathScan(n) => {
            push_node(out, n.plan.as_deref());
            if let Some(child) = &n.path {
                out.push(NodeRef::JsonTablePath(child));
            }
            push_node(out, n.child.as_deref());
        }
        NodeRef::JsonTableSiblingJoin(n) => {
            push_node(out, n.plan.as_deref());
            push_node(out, n.lplan.as_deref());
            push_node(out, n.rplan.as_deref());
        }
        NodeRef::JsonArgument(n) => {
            if let Some(child) = &n.val {
                out.push(NodeRef::JsonValueExpr(child));
            }
        }
        NodeRef::JsonFuncExpr(n) => {
            if let Some(child) = &n.context_item {
                out.push(NodeRef::JsonValueExpr(child));
            }
            push_node(out, n.pathspec.as_deref());
            push_nodes(out, &n.passing);
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
            if let Some(child) = &n.on_empty {
                out.push(NodeRef::JsonBehavior(child));
            }
            if let Some(child) = &n.on_error {
                out.push(NodeRef::JsonBehavior(child));
            }
        }
        NodeRef::JsonTablePathSpec(n) => {
            push_node(out, n.string.as_deref());
        }
        NodeRef::JsonTable(n) => {
            if let Some(child) = &n.context_item {
                out.push(NodeRef::JsonValueExpr(child));
            }
            if let Some(child) = &n.pathspec {
                out.push(NodeRef::JsonTablePathSpec(child));
            }
            push_nodes(out, &n.passing);
            push_nodes(out, &n.columns);
            if let Some(child) = &n.on_error {
                out.push(NodeRef::JsonBehavior(child));
            }
            if let Some(child) = &n.alias {
                out.push(NodeRef::Alias(child));
            }
        }
        NodeRef::JsonTableColumn(n) => {
            if let Some(child) = &n.type_name {
                out.push(NodeRef::TypeName(child));
            }
            if let Some(child) = &n.pathspec {
                out.push(NodeRef::JsonTablePathSpec(child));
            }
            if let Some(child) = &n.format {
                out.push(NodeRef::JsonFormat(child));
            }
            push_nodes(out, &n.columns);
            if let Some(child) = &n.on_empty {
                out.push(NodeRef::JsonBehavior(child));
            }
            if let Some(child) = &n.on_error {
                out.push(NodeRef::JsonBehavior(child));
            }
        }
        NodeRef::JsonParseExpr(n) => {
            if let Some(child) = &n.expr {
                out.push(NodeRef::JsonValueExpr(child));
            }
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
        }
        NodeRef::JsonScalarExpr(n) => {
            push_node(out, n.expr.as_deref());
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
        }
        NodeRef::JsonSerializeExpr(n) => {
            if let Some(child) = &n.expr {
                out.push(NodeRef::JsonValueExpr(child));
            }
            if let Some(child) = &n.output {
                out.push(NodeRef::JsonOutput(child));
            }
        }
        NodeRef::RangeTblRef(_)
        | NodeRef::ClosePortalStmt(_)
        | NodeRef::FetchStmt(_)
        | NodeRef::NotifyStmt(_)
        | NodeRef::ListenStmt(_)
        | NodeRef::UnlistenStmt(_)
        | NodeRef::LoadStmt(_)
        | NodeRef::VariableShowStmt(_)
        | NodeRef::DiscardStmt(_)
        | NodeRef::CheckPointStmt(_)
        | NodeRef::DeallocateStmt(_)
        | NodeRef::DropTableSpaceStmt(_)
        | NodeRef::AlterEventTrigStmt(_)
        | NodeRef::ReplicaIdentityStmt(_)
        | NodeRef::DropSubscriptionStmt(_)
        | NodeRef::ParamRef(_)
        | NodeRef::AStar(_)
        | NodeRef::SortGroupClause(_)
        | NodeRef::RowMarkClause(_)
        | NodeRef::RoleSpec(_)
        | NodeRef::TriggerTransition(_)
        | NodeRef::InlineCodeBlock(_)
        | NodeRef::CallContext(_)
        | NodeRef::Integer(_)
        | NodeRef::Float(_)
        | NodeRef::Boolean(_)
        | NodeRef::String(_)
        | NodeRef::BitString(_)
        | NodeRef::AlterDatabaseRefreshCollStmt(_)
        | NodeRef::JsonFormat(_)
        | NodeRef::RtepermissionInfo(_)
        | NodeRef::JsonTablePath(_)
        | NodeRef::SinglePartitionSpec(_) => {}
    }
}

fn push_nodes<'a>(out: &mut Vec<NodeRef<'a>>, nodes: &'a [Node]) {
    for node in nodes {
        push_node(out, Some(node));
    }
}

fn push_node<'a>(out: &mut Vec<NodeRef<'a>>, node: Option<&'a Node>) {
    if let Some(node) = node.and_then(|node| node.node.as_ref()) {
        out.push(node.to_ref());
    }
}
